# Generated by Django 5.1.1 on 2024-09-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("genre", models.CharField(max_length=50)),
                ("runtime", models.IntegerField()),
                ("description", models.TextField()),
                ("rating", models.FloatField()),
                ("launch_date", models.DateTimeField()),
            ],
        ),
    ]
