# Generated by Django 5.1.1 on 2024-09-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_movie_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Image",
            field=models.ImageField(default="defaultmovie.jpeg", upload_to="movie_img"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
