# Generated by Django 5.1.1 on 2024-09-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_price_wallet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.DurationField(),
        ),
    ]
