# Generated by Django 5.1.1 on 2024-09-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_runtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="runtime",
            field=models.CharField(max_length=7),
        ),
    ]
